// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: v1alpha/tracker/tracker.proto

package tracker

import (
	context "context"
	fmt "fmt"
	deps "github.com/deps-cloud/api/v1alpha/deps"
	schema "github.com/deps-cloud/api/v1alpha/schema"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SourceRequest struct {
	Source               *schema.Source                   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	ManagementFiles      []*deps.DependencyManagementFile `protobuf:"bytes,2,rep,name=managementFiles,proto3" json:"managementFiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *SourceRequest) Reset()         { *m = SourceRequest{} }
func (m *SourceRequest) String() string { return proto.CompactTextString(m) }
func (*SourceRequest) ProtoMessage()    {}
func (*SourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{0}
}
func (m *SourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceRequest.Unmarshal(m, b)
}
func (m *SourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceRequest.Marshal(b, m, deterministic)
}
func (m *SourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceRequest.Merge(m, src)
}
func (m *SourceRequest) XXX_Size() int {
	return xxx_messageInfo_SourceRequest.Size(m)
}
func (m *SourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SourceRequest proto.InternalMessageInfo

func (m *SourceRequest) GetSource() *schema.Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *SourceRequest) GetManagementFiles() []*deps.DependencyManagementFile {
	if m != nil {
		return m.ManagementFiles
	}
	return nil
}

type ListRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{1}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type TrackResponse struct {
	Tracking             bool     `protobuf:"varint,1,opt,name=tracking,proto3" json:"tracking,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackResponse) Reset()         { *m = TrackResponse{} }
func (m *TrackResponse) String() string { return proto.CompactTextString(m) }
func (*TrackResponse) ProtoMessage()    {}
func (*TrackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{2}
}
func (m *TrackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackResponse.Unmarshal(m, b)
}
func (m *TrackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackResponse.Marshal(b, m, deterministic)
}
func (m *TrackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackResponse.Merge(m, src)
}
func (m *TrackResponse) XXX_Size() int {
	return xxx_messageInfo_TrackResponse.Size(m)
}
func (m *TrackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrackResponse proto.InternalMessageInfo

func (m *TrackResponse) GetTracking() bool {
	if m != nil {
		return m.Tracking
	}
	return false
}

type ListSourceResponse struct {
	Page                 int32            `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32            `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Sources              []*schema.Source `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListSourceResponse) Reset()         { *m = ListSourceResponse{} }
func (m *ListSourceResponse) String() string { return proto.CompactTextString(m) }
func (*ListSourceResponse) ProtoMessage()    {}
func (*ListSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{3}
}
func (m *ListSourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSourceResponse.Unmarshal(m, b)
}
func (m *ListSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSourceResponse.Marshal(b, m, deterministic)
}
func (m *ListSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSourceResponse.Merge(m, src)
}
func (m *ListSourceResponse) XXX_Size() int {
	return xxx_messageInfo_ListSourceResponse.Size(m)
}
func (m *ListSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSourceResponse proto.InternalMessageInfo

func (m *ListSourceResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListSourceResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListSourceResponse) GetSources() []*schema.Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

type ListModuleResponse struct {
	Page                 int32            `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32            `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Modules              []*schema.Module `protobuf:"bytes,3,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListModuleResponse) Reset()         { *m = ListModuleResponse{} }
func (m *ListModuleResponse) String() string { return proto.CompactTextString(m) }
func (*ListModuleResponse) ProtoMessage()    {}
func (*ListModuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{4}
}
func (m *ListModuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModuleResponse.Unmarshal(m, b)
}
func (m *ListModuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModuleResponse.Marshal(b, m, deterministic)
}
func (m *ListModuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModuleResponse.Merge(m, src)
}
func (m *ListModuleResponse) XXX_Size() int {
	return xxx_messageInfo_ListModuleResponse.Size(m)
}
func (m *ListModuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListModuleResponse proto.InternalMessageInfo

func (m *ListModuleResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListModuleResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListModuleResponse) GetModules() []*schema.Module {
	if m != nil {
		return m.Modules
	}
	return nil
}

type ManagedSource struct {
	Source               *schema.Source  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Manages              *schema.Manages `protobuf:"bytes,2,opt,name=manages,proto3" json:"manages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ManagedSource) Reset()         { *m = ManagedSource{} }
func (m *ManagedSource) String() string { return proto.CompactTextString(m) }
func (*ManagedSource) ProtoMessage()    {}
func (*ManagedSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{5}
}
func (m *ManagedSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagedSource.Unmarshal(m, b)
}
func (m *ManagedSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagedSource.Marshal(b, m, deterministic)
}
func (m *ManagedSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagedSource.Merge(m, src)
}
func (m *ManagedSource) XXX_Size() int {
	return xxx_messageInfo_ManagedSource.Size(m)
}
func (m *ManagedSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagedSource.DiscardUnknown(m)
}

var xxx_messageInfo_ManagedSource proto.InternalMessageInfo

func (m *ManagedSource) GetSource() *schema.Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *ManagedSource) GetManages() *schema.Manages {
	if m != nil {
		return m.Manages
	}
	return nil
}

type ManagedModule struct {
	Manages              *schema.Manages `protobuf:"bytes,1,opt,name=manages,proto3" json:"manages,omitempty"`
	Module               *schema.Module  `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ManagedModule) Reset()         { *m = ManagedModule{} }
func (m *ManagedModule) String() string { return proto.CompactTextString(m) }
func (*ManagedModule) ProtoMessage()    {}
func (*ManagedModule) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{6}
}
func (m *ManagedModule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagedModule.Unmarshal(m, b)
}
func (m *ManagedModule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagedModule.Marshal(b, m, deterministic)
}
func (m *ManagedModule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagedModule.Merge(m, src)
}
func (m *ManagedModule) XXX_Size() int {
	return xxx_messageInfo_ManagedModule.Size(m)
}
func (m *ManagedModule) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagedModule.DiscardUnknown(m)
}

var xxx_messageInfo_ManagedModule proto.InternalMessageInfo

func (m *ManagedModule) GetManages() *schema.Manages {
	if m != nil {
		return m.Manages
	}
	return nil
}

func (m *ManagedModule) GetModule() *schema.Module {
	if m != nil {
		return m.Module
	}
	return nil
}

type ListSourcesResponse struct {
	Sources              []*ManagedSource `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListSourcesResponse) Reset()         { *m = ListSourcesResponse{} }
func (m *ListSourcesResponse) String() string { return proto.CompactTextString(m) }
func (*ListSourcesResponse) ProtoMessage()    {}
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{7}
}
func (m *ListSourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSourcesResponse.Unmarshal(m, b)
}
func (m *ListSourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSourcesResponse.Marshal(b, m, deterministic)
}
func (m *ListSourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSourcesResponse.Merge(m, src)
}
func (m *ListSourcesResponse) XXX_Size() int {
	return xxx_messageInfo_ListSourcesResponse.Size(m)
}
func (m *ListSourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSourcesResponse proto.InternalMessageInfo

func (m *ListSourcesResponse) GetSources() []*ManagedSource {
	if m != nil {
		return m.Sources
	}
	return nil
}

type ListManagedResponse struct {
	Modules              []*ManagedModule `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListManagedResponse) Reset()         { *m = ListManagedResponse{} }
func (m *ListManagedResponse) String() string { return proto.CompactTextString(m) }
func (*ListManagedResponse) ProtoMessage()    {}
func (*ListManagedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{8}
}
func (m *ListManagedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListManagedResponse.Unmarshal(m, b)
}
func (m *ListManagedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListManagedResponse.Marshal(b, m, deterministic)
}
func (m *ListManagedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListManagedResponse.Merge(m, src)
}
func (m *ListManagedResponse) XXX_Size() int {
	return xxx_messageInfo_ListManagedResponse.Size(m)
}
func (m *ListManagedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListManagedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListManagedResponse proto.InternalMessageInfo

func (m *ListManagedResponse) GetModules() []*ManagedModule {
	if m != nil {
		return m.Modules
	}
	return nil
}

type DependencyRequest struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Organization         string   `protobuf:"bytes,5,opt,name=organization,proto3" json:"organization,omitempty"`
	Module               string   `protobuf:"bytes,6,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DependencyRequest) Reset()         { *m = DependencyRequest{} }
func (m *DependencyRequest) String() string { return proto.CompactTextString(m) }
func (*DependencyRequest) ProtoMessage()    {}
func (*DependencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{9}
}
func (m *DependencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependencyRequest.Unmarshal(m, b)
}
func (m *DependencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependencyRequest.Marshal(b, m, deterministic)
}
func (m *DependencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependencyRequest.Merge(m, src)
}
func (m *DependencyRequest) XXX_Size() int {
	return xxx_messageInfo_DependencyRequest.Size(m)
}
func (m *DependencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DependencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DependencyRequest proto.InternalMessageInfo

func (m *DependencyRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *DependencyRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *DependencyRequest) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

type Dependency struct {
	Depends              *schema.Depends `protobuf:"bytes,1,opt,name=depends,proto3" json:"depends,omitempty"`
	Module               *schema.Module  `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Dependency) Reset()         { *m = Dependency{} }
func (m *Dependency) String() string { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()    {}
func (*Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{10}
}
func (m *Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependency.Unmarshal(m, b)
}
func (m *Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependency.Marshal(b, m, deterministic)
}
func (m *Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependency.Merge(m, src)
}
func (m *Dependency) XXX_Size() int {
	return xxx_messageInfo_Dependency.Size(m)
}
func (m *Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_Dependency proto.InternalMessageInfo

func (m *Dependency) GetDepends() *schema.Depends {
	if m != nil {
		return m.Depends
	}
	return nil
}

func (m *Dependency) GetModule() *schema.Module {
	if m != nil {
		return m.Module
	}
	return nil
}

type ListDependentsResponse struct {
	Dependents           []*Dependency `protobuf:"bytes,1,rep,name=dependents,proto3" json:"dependents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListDependentsResponse) Reset()         { *m = ListDependentsResponse{} }
func (m *ListDependentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListDependentsResponse) ProtoMessage()    {}
func (*ListDependentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{11}
}
func (m *ListDependentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDependentsResponse.Unmarshal(m, b)
}
func (m *ListDependentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDependentsResponse.Marshal(b, m, deterministic)
}
func (m *ListDependentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDependentsResponse.Merge(m, src)
}
func (m *ListDependentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListDependentsResponse.Size(m)
}
func (m *ListDependentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDependentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDependentsResponse proto.InternalMessageInfo

func (m *ListDependentsResponse) GetDependents() []*Dependency {
	if m != nil {
		return m.Dependents
	}
	return nil
}

type ListDependenciesResponse struct {
	Dependencies         []*Dependency `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListDependenciesResponse) Reset()         { *m = ListDependenciesResponse{} }
func (m *ListDependenciesResponse) String() string { return proto.CompactTextString(m) }
func (*ListDependenciesResponse) ProtoMessage()    {}
func (*ListDependenciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{12}
}
func (m *ListDependenciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDependenciesResponse.Unmarshal(m, b)
}
func (m *ListDependenciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDependenciesResponse.Marshal(b, m, deterministic)
}
func (m *ListDependenciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDependenciesResponse.Merge(m, src)
}
func (m *ListDependenciesResponse) XXX_Size() int {
	return xxx_messageInfo_ListDependenciesResponse.Size(m)
}
func (m *ListDependenciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDependenciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDependenciesResponse proto.InternalMessageInfo

func (m *ListDependenciesResponse) GetDependencies() []*Dependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type TopologyTier struct {
	Tier                 []*Dependency `protobuf:"bytes,1,rep,name=tier,proto3" json:"tier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TopologyTier) Reset()         { *m = TopologyTier{} }
func (m *TopologyTier) String() string { return proto.CompactTextString(m) }
func (*TopologyTier) ProtoMessage()    {}
func (*TopologyTier) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{13}
}
func (m *TopologyTier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologyTier.Unmarshal(m, b)
}
func (m *TopologyTier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologyTier.Marshal(b, m, deterministic)
}
func (m *TopologyTier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyTier.Merge(m, src)
}
func (m *TopologyTier) XXX_Size() int {
	return xxx_messageInfo_TopologyTier.Size(m)
}
func (m *TopologyTier) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyTier.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyTier proto.InternalMessageInfo

func (m *TopologyTier) GetTier() []*Dependency {
	if m != nil {
		return m.Tier
	}
	return nil
}

type ListDependentsTieredResponse struct {
	Tiers                []*TopologyTier `protobuf:"bytes,1,rep,name=tiers,proto3" json:"tiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListDependentsTieredResponse) Reset()         { *m = ListDependentsTieredResponse{} }
func (m *ListDependentsTieredResponse) String() string { return proto.CompactTextString(m) }
func (*ListDependentsTieredResponse) ProtoMessage()    {}
func (*ListDependentsTieredResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{14}
}
func (m *ListDependentsTieredResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDependentsTieredResponse.Unmarshal(m, b)
}
func (m *ListDependentsTieredResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDependentsTieredResponse.Marshal(b, m, deterministic)
}
func (m *ListDependentsTieredResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDependentsTieredResponse.Merge(m, src)
}
func (m *ListDependentsTieredResponse) XXX_Size() int {
	return xxx_messageInfo_ListDependentsTieredResponse.Size(m)
}
func (m *ListDependentsTieredResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDependentsTieredResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDependentsTieredResponse proto.InternalMessageInfo

func (m *ListDependentsTieredResponse) GetTiers() []*TopologyTier {
	if m != nil {
		return m.Tiers
	}
	return nil
}

type ListDependenciesTieredResponse struct {
	Tiers                []*TopologyTier `protobuf:"bytes,1,rep,name=tiers,proto3" json:"tiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListDependenciesTieredResponse) Reset()         { *m = ListDependenciesTieredResponse{} }
func (m *ListDependenciesTieredResponse) String() string { return proto.CompactTextString(m) }
func (*ListDependenciesTieredResponse) ProtoMessage()    {}
func (*ListDependenciesTieredResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b64d82f5e279343, []int{15}
}
func (m *ListDependenciesTieredResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDependenciesTieredResponse.Unmarshal(m, b)
}
func (m *ListDependenciesTieredResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDependenciesTieredResponse.Marshal(b, m, deterministic)
}
func (m *ListDependenciesTieredResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDependenciesTieredResponse.Merge(m, src)
}
func (m *ListDependenciesTieredResponse) XXX_Size() int {
	return xxx_messageInfo_ListDependenciesTieredResponse.Size(m)
}
func (m *ListDependenciesTieredResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDependenciesTieredResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDependenciesTieredResponse proto.InternalMessageInfo

func (m *ListDependenciesTieredResponse) GetTiers() []*TopologyTier {
	if m != nil {
		return m.Tiers
	}
	return nil
}

func init() {
	proto.RegisterType((*SourceRequest)(nil), "cloud.deps.api.v1alpha.tracker.SourceRequest")
	proto.RegisterType((*ListRequest)(nil), "cloud.deps.api.v1alpha.tracker.ListRequest")
	proto.RegisterType((*TrackResponse)(nil), "cloud.deps.api.v1alpha.tracker.TrackResponse")
	proto.RegisterType((*ListSourceResponse)(nil), "cloud.deps.api.v1alpha.tracker.ListSourceResponse")
	proto.RegisterType((*ListModuleResponse)(nil), "cloud.deps.api.v1alpha.tracker.ListModuleResponse")
	proto.RegisterType((*ManagedSource)(nil), "cloud.deps.api.v1alpha.tracker.ManagedSource")
	proto.RegisterType((*ManagedModule)(nil), "cloud.deps.api.v1alpha.tracker.ManagedModule")
	proto.RegisterType((*ListSourcesResponse)(nil), "cloud.deps.api.v1alpha.tracker.ListSourcesResponse")
	proto.RegisterType((*ListManagedResponse)(nil), "cloud.deps.api.v1alpha.tracker.ListManagedResponse")
	proto.RegisterType((*DependencyRequest)(nil), "cloud.deps.api.v1alpha.tracker.DependencyRequest")
	proto.RegisterType((*Dependency)(nil), "cloud.deps.api.v1alpha.tracker.Dependency")
	proto.RegisterType((*ListDependentsResponse)(nil), "cloud.deps.api.v1alpha.tracker.ListDependentsResponse")
	proto.RegisterType((*ListDependenciesResponse)(nil), "cloud.deps.api.v1alpha.tracker.ListDependenciesResponse")
	proto.RegisterType((*TopologyTier)(nil), "cloud.deps.api.v1alpha.tracker.TopologyTier")
	proto.RegisterType((*ListDependentsTieredResponse)(nil), "cloud.deps.api.v1alpha.tracker.ListDependentsTieredResponse")
	proto.RegisterType((*ListDependenciesTieredResponse)(nil), "cloud.deps.api.v1alpha.tracker.ListDependenciesTieredResponse")
}

func init() { proto.RegisterFile("v1alpha/tracker/tracker.proto", fileDescriptor_3b64d82f5e279343) }

var fileDescriptor_3b64d82f5e279343 = []byte{
	// 979 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x4f, 0x6f, 0xdc, 0x44,
	0x14, 0xd7, 0x6c, 0xb2, 0x69, 0x78, 0x49, 0x68, 0x19, 0x50, 0x6a, 0x5c, 0x28, 0x61, 0x04, 0x51,
	0x68, 0x1a, 0x5b, 0x71, 0x69, 0x5a, 0xa1, 0x12, 0x50, 0x85, 0x40, 0x42, 0xb4, 0x07, 0x37, 0xa7,
	0x1e, 0xa8, 0x26, 0xf6, 0xc8, 0x6b, 0xba, 0xeb, 0x31, 0xf6, 0x6c, 0xd1, 0x82, 0x10, 0x82, 0x13,
	0x02, 0x21, 0x21, 0x71, 0xe7, 0xce, 0x85, 0x1e, 0x91, 0x38, 0xf1, 0x05, 0x38, 0xf5, 0x2b, 0xf0,
	0x05, 0xf8, 0x06, 0xc8, 0xf3, 0xc7, 0xff, 0xb6, 0x65, 0xbd, 0xbb, 0x55, 0x2f, 0x59, 0x7b, 0x66,
	0xde, 0x7b, 0xbf, 0xf7, 0xfb, 0xcd, 0x7b, 0x2f, 0x86, 0x57, 0x1f, 0x1c, 0xd2, 0x61, 0x3a, 0xa0,
	0xae, 0xc8, 0x68, 0x70, 0x9f, 0x65, 0xe6, 0xd7, 0x49, 0x33, 0x2e, 0x38, 0xbe, 0x18, 0x0c, 0xf9,
	0x38, 0x74, 0x42, 0x96, 0xe6, 0x0e, 0x4d, 0x63, 0x47, 0x9f, 0x76, 0xf4, 0x29, 0xfb, 0xbc, 0x31,
	0x2f, 0x4e, 0xc8, 0x3f, 0xca, 0xd0, 0xbe, 0x60, 0x36, 0xf2, 0x60, 0xc0, 0x46, 0xe6, 0x47, 0x6f,
	0xde, 0x8d, 0x62, 0x31, 0x18, 0x9f, 0x3a, 0x01, 0x1f, 0xb9, 0x51, 0x96, 0x06, 0x07, 0x2c, 0xe0,
	0xf9, 0x24, 0x17, 0x4c, 0xbf, 0x46, 0x54, 0xb0, 0x2f, 0xe8, 0xc4, 0x15, 0x83, 0x38, 0x0b, 0xef,
	0xa5, 0x34, 0x13, 0x13, 0x37, 0xe2, 0x3c, 0x1a, 0x32, 0x9a, 0xc6, 0xb9, 0x7e, 0x74, 0x69, 0x1a,
	0xbb, 0x34, 0x49, 0xb8, 0xa0, 0x22, 0xe6, 0x89, 0x0e, 0x4c, 0x1e, 0x22, 0xd8, 0xba, 0xc3, 0xc7,
	0x59, 0xc0, 0x7c, 0xf6, 0xf9, 0x98, 0xe5, 0x02, 0xbf, 0x0b, 0x6b, 0xb9, 0x5c, 0xb0, 0xd0, 0x0e,
	0xda, 0xdb, 0xf0, 0xde, 0x74, 0x9e, 0x90, 0x94, 0xc6, 0xa8, 0xad, 0xb5, 0x11, 0xbe, 0x07, 0x67,
	0x47, 0x34, 0xa1, 0x11, 0x1b, 0xb1, 0x44, 0x7c, 0x18, 0x0f, 0x59, 0x6e, 0xf5, 0x76, 0x56, 0xf6,
	0x36, 0xbc, 0xab, 0x4f, 0xf2, 0x23, 0x17, 0x3e, 0x60, 0x29, 0x4b, 0x42, 0x96, 0x04, 0x93, 0x5b,
	0x0d, 0x6b, 0xbf, 0xed, 0x8d, 0x5c, 0x83, 0x8d, 0x4f, 0xe2, 0x5c, 0x18, 0xb8, 0x18, 0x56, 0x53,
	0x1a, 0x29, 0xb0, 0x7d, 0x5f, 0x3e, 0xe3, 0x97, 0xa0, 0x1f, 0xf0, 0x71, 0x22, 0xac, 0x9e, 0x5c,
	0x54, 0x2f, 0x64, 0x1f, 0xb6, 0x4e, 0x0a, 0x1d, 0x7c, 0x96, 0xa7, 0x3c, 0xc9, 0x19, 0xb6, 0x61,
	0x5d, 0x0a, 0x13, 0x27, 0x91, 0x34, 0x5f, 0xf7, 0xcb, 0x77, 0xf2, 0x0d, 0xe0, 0x22, 0x8a, 0xa1,
	0x46, 0x5b, 0x74, 0x0e, 0x86, 0xdf, 0x83, 0x33, 0x8a, 0x90, 0xdc, 0x5a, 0x91, 0xe9, 0x77, 0xa4,
	0xd1, 0x58, 0x19, 0x00, 0xb7, 0x78, 0x38, 0x1e, 0x2e, 0x08, 0x60, 0x24, 0x6d, 0xbb, 0x02, 0xd0,
	0x91, 0x8c, 0x15, 0xf9, 0x19, 0xc1, 0x96, 0xd2, 0x22, 0x54, 0xd8, 0x96, 0xbd, 0x19, 0xef, 0xc3,
	0x19, 0xa5, 0x65, 0x2e, 0x91, 0x6e, 0x78, 0xbb, 0xb3, 0x10, 0xa9, 0xd3, 0xbe, 0x31, 0xab, 0x43,
	0x52, 0x68, 0xeb, 0x3e, 0xd1, 0x42, 0x3e, 0x8b, 0xa4, 0x54, 0xc6, 0x1a, 0x54, 0x47, 0x9a, 0xb4,
	0x11, 0xf9, 0x14, 0x5e, 0xac, 0xee, 0x49, 0x5e, 0xea, 0xf4, 0x51, 0x25, 0x3f, 0x92, 0xec, 0x1f,
	0x38, 0xff, 0xdf, 0x1a, 0x9c, 0x06, 0xd5, 0xd5, 0x35, 0xd0, 0xfe, 0xf5, 0x6e, 0xdd, 0xbf, 0x51,
	0x77, 0x3e, 0xff, 0x6d, 0x95, 0xef, 0xc3, 0x0b, 0x55, 0xe9, 0x99, 0x9a, 0xb2, 0x61, 0x7d, 0x48,
	0x93, 0x68, 0x6c, 0x6e, 0xda, 0x73, 0x7e, 0xf9, 0x8e, 0x09, 0x6c, 0xf2, 0x2c, 0xa2, 0x49, 0xfc,
	0xa5, 0xec, 0x23, 0x56, 0x5f, 0xee, 0x37, 0xd6, 0xf0, 0x76, 0xc9, 0xe9, 0x9a, 0xdc, 0x35, 0x64,
	0xfd, 0x84, 0x00, 0xaa, 0x68, 0x85, 0x78, 0xa1, 0x7c, 0xeb, 0x2a, 0x9e, 0xb2, 0xcd, 0x7d, 0x63,
	0xb6, 0xac, 0x78, 0x21, 0x6c, 0x17, 0xe4, 0x1a, 0x48, 0xa2, 0xd2, 0xef, 0x63, 0x80, 0xb0, 0x5c,
	0xd5, 0x14, 0x5f, 0x9a, 0x45, 0x71, 0x8d, 0xc8, 0x9a, 0x35, 0xf9, 0x0c, 0xac, 0x7a, 0x94, 0x20,
	0xae, 0xdd, 0x93, 0xdb, 0xb0, 0x19, 0xd6, 0xd6, 0x17, 0x88, 0xd4, 0xb0, 0x27, 0xb7, 0x61, 0xf3,
	0x84, 0xa7, 0x7c, 0xc8, 0xa3, 0xc9, 0x49, 0xcc, 0x32, 0x7c, 0x0c, 0xab, 0x22, 0x66, 0xd9, 0x02,
	0x7e, 0xa5, 0x1d, 0x39, 0x85, 0x57, 0x9a, 0x0c, 0x15, 0x5e, 0x6b, 0xf7, 0xf0, 0x26, 0xf4, 0x8b,
	0x73, 0x06, 0xf8, 0xe5, 0x59, 0x01, 0xea, 0xe0, 0x7c, 0x65, 0x4a, 0x42, 0xb8, 0xd8, 0xe6, 0xe7,
	0xe9, 0x47, 0xf1, 0x7e, 0xed, 0x99, 0x41, 0x77, 0x87, 0x65, 0x0f, 0xe2, 0x80, 0xe1, 0x6f, 0x11,
	0xac, 0x16, 0x81, 0xf1, 0xfe, 0x2c, 0x7f, 0xb5, 0x79, 0x63, 0x7b, 0x5d, 0x0e, 0x37, 0xc7, 0x06,
	0xb1, 0xbe, 0x7b, 0xf4, 0xcf, 0x2f, 0x3d, 0x8c, 0xcf, 0xb9, 0xe5, 0x98, 0x57, 0xe5, 0x8d, 0xbf,
	0x47, 0xd0, 0x97, 0x43, 0x09, 0xcf, 0x2c, 0xe0, 0xc6, 0x94, 0xb6, 0x67, 0x1e, 0x6f, 0x8c, 0x3a,
	0xf2, 0xba, 0x44, 0x70, 0x81, 0x6c, 0xb7, 0x11, 0xa8, 0x7f, 0x60, 0xde, 0x41, 0x97, 0xbc, 0xdf,
	0x57, 0x60, 0x4b, 0xd5, 0xc7, 0x33, 0x20, 0xa8, 0x39, 0xd6, 0x1e, 0x43, 0x90, 0xee, 0x4f, 0xf8,
	0x07, 0xa4, 0xc6, 0xbd, 0x6e, 0xb0, 0xb8, 0x5b, 0x85, 0xdb, 0x57, 0xba, 0xab, 0x54, 0x16, 0x23,
	0x79, 0x4d, 0xa2, 0x78, 0x19, 0x9f, 0x6f, 0xa3, 0xd0, 0x64, 0xe1, 0x1f, 0x35, 0x18, 0xdd, 0x4b,
	0x71, 0xb7, 0x01, 0xd8, 0x0d, 0x4c, 0xab, 0xc3, 0x93, 0x1d, 0x09, 0xc6, 0xc6, 0xd6, 0x14, 0x18,
	0x35, 0xb9, 0x42, 0xef, 0xdf, 0x5e, 0xbd, 0x77, 0x1b, 0xd1, 0x7e, 0x43, 0xf0, 0x7c, 0xb3, 0x64,
	0xf1, 0xe1, 0x1c, 0x65, 0xaf, 0x45, 0x3c, 0xea, 0x02, 0x79, 0xba, 0x6f, 0x92, 0xcb, 0x12, 0xf5,
	0x2e, 0x7e, 0xa3, 0x44, 0x1d, 0x65, 0x34, 0x1d, 0xb8, 0x5f, 0x99, 0xf9, 0xf1, 0xb5, 0x5b, 0x75,
	0x46, 0xfc, 0x10, 0xc1, 0xb9, 0x76, 0xe9, 0x2f, 0x82, 0xf6, 0xfa, 0x3c, 0x68, 0xeb, 0xfd, 0x97,
	0x38, 0x12, 0xef, 0x1e, 0xde, 0x9d, 0x8d, 0xb7, 0xb0, 0xf3, 0xfe, 0x58, 0x83, 0xb3, 0xa6, 0xbb,
	0x18, 0xc6, 0xff, 0x44, 0xed, 0x31, 0x62, 0x4e, 0x3c, 0x4b, 0xe6, 0xaf, 0xca, 0x4c, 0x5c, 0x7c,
	0xd0, 0x85, 0x79, 0x57, 0x18, 0x84, 0x7f, 0xa3, 0xa9, 0x0e, 0x5f, 0x6b, 0x9e, 0x2c, 0x5c, 0x24,
	0x85, 0x1b, 0xf3, 0xa5, 0xd0, 0x6c, 0xf6, 0xe4, 0x86, 0x4c, 0xe4, 0x08, 0xbf, 0x3d, 0x57, 0x22,
	0xae, 0x50, 0x70, 0xff, 0x42, 0xd3, 0xd3, 0x76, 0x19, 0x39, 0x16, 0xbf, 0x5a, 0xd7, 0x64, 0x1e,
	0x87, 0xd8, 0xed, 0x76, 0xb5, 0x2a, 0x49, 0x1e, 0xa1, 0xc7, 0x0c, 0xc4, 0xa5, 0x45, 0x39, 0x9e,
	0x37, 0x91, 0x96, 0x2c, 0xc7, 0x32, 0x9d, 0xeb, 0xf8, 0x68, 0xce, 0x74, 0xb4, 0x30, 0x37, 0xf7,
	0xef, 0xbe, 0x55, 0xfb, 0x8c, 0x2d, 0x50, 0x1c, 0x48, 0x40, 0xf2, 0xbb, 0xb4, 0xf5, 0x55, 0x7d,
	0xba, 0x26, 0x3f, 0x4e, 0xaf, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x0a, 0x3b, 0xae, 0x6f,
	0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SourceServiceClient is the client API for SourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SourceServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListSourceResponse, error)
	Track(ctx context.Context, in *SourceRequest, opts ...grpc.CallOption) (*TrackResponse, error)
}

type sourceServiceClient struct {
	cc *grpc.ClientConn
}

func NewSourceServiceClient(cc *grpc.ClientConn) SourceServiceClient {
	return &sourceServiceClient{cc}
}

func (c *sourceServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListSourceResponse, error) {
	out := new(ListSourceResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.api.v1alpha.tracker.SourceService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) Track(ctx context.Context, in *SourceRequest, opts ...grpc.CallOption) (*TrackResponse, error) {
	out := new(TrackResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.api.v1alpha.tracker.SourceService/Track", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceServiceServer is the server API for SourceService service.
type SourceServiceServer interface {
	List(context.Context, *ListRequest) (*ListSourceResponse, error)
	Track(context.Context, *SourceRequest) (*TrackResponse, error)
}

// UnimplementedSourceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSourceServiceServer struct {
}

func (*UnimplementedSourceServiceServer) List(ctx context.Context, req *ListRequest) (*ListSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedSourceServiceServer) Track(ctx context.Context, req *SourceRequest) (*TrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Track not implemented")
}

func RegisterSourceServiceServer(s *grpc.Server, srv SourceServiceServer) {
	s.RegisterService(&_SourceService_serviceDesc, srv)
}

func _SourceService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.api.v1alpha.tracker.SourceService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_Track_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Track(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.api.v1alpha.tracker.SourceService/Track",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Track(ctx, req.(*SourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SourceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.deps.api.v1alpha.tracker.SourceService",
	HandlerType: (*SourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SourceService_List_Handler,
		},
		{
			MethodName: "Track",
			Handler:    _SourceService_Track_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha/tracker/tracker.proto",
}

// ModuleServiceClient is the client API for ModuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModuleServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListModuleResponse, error)
	ListSources(ctx context.Context, in *schema.Module, opts ...grpc.CallOption) (*ListSourcesResponse, error)
	ListManaged(ctx context.Context, in *schema.Source, opts ...grpc.CallOption) (*ListManagedResponse, error)
}

type moduleServiceClient struct {
	cc *grpc.ClientConn
}

func NewModuleServiceClient(cc *grpc.ClientConn) ModuleServiceClient {
	return &moduleServiceClient{cc}
}

func (c *moduleServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListModuleResponse, error) {
	out := new(ListModuleResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.api.v1alpha.tracker.ModuleService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) ListSources(ctx context.Context, in *schema.Module, opts ...grpc.CallOption) (*ListSourcesResponse, error) {
	out := new(ListSourcesResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.api.v1alpha.tracker.ModuleService/ListSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) ListManaged(ctx context.Context, in *schema.Source, opts ...grpc.CallOption) (*ListManagedResponse, error) {
	out := new(ListManagedResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.api.v1alpha.tracker.ModuleService/ListManaged", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServiceServer is the server API for ModuleService service.
type ModuleServiceServer interface {
	List(context.Context, *ListRequest) (*ListModuleResponse, error)
	ListSources(context.Context, *schema.Module) (*ListSourcesResponse, error)
	ListManaged(context.Context, *schema.Source) (*ListManagedResponse, error)
}

// UnimplementedModuleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedModuleServiceServer struct {
}

func (*UnimplementedModuleServiceServer) List(ctx context.Context, req *ListRequest) (*ListModuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedModuleServiceServer) ListSources(ctx context.Context, req *schema.Module) (*ListSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSources not implemented")
}
func (*UnimplementedModuleServiceServer) ListManaged(ctx context.Context, req *schema.Source) (*ListManagedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListManaged not implemented")
}

func RegisterModuleServiceServer(s *grpc.Server, srv ModuleServiceServer) {
	s.RegisterService(&_ModuleService_serviceDesc, srv)
}

func _ModuleService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.api.v1alpha.tracker.ModuleService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(schema.Module)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.api.v1alpha.tracker.ModuleService/ListSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).ListSources(ctx, req.(*schema.Module))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_ListManaged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(schema.Source)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).ListManaged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.api.v1alpha.tracker.ModuleService/ListManaged",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).ListManaged(ctx, req.(*schema.Source))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModuleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.deps.api.v1alpha.tracker.ModuleService",
	HandlerType: (*ModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ModuleService_List_Handler,
		},
		{
			MethodName: "ListSources",
			Handler:    _ModuleService_ListSources_Handler,
		},
		{
			MethodName: "ListManaged",
			Handler:    _ModuleService_ListManaged_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha/tracker/tracker.proto",
}

// DependencyServiceClient is the client API for DependencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DependencyServiceClient interface {
	ListDependents(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (*ListDependentsResponse, error)
	ListDependencies(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (*ListDependenciesResponse, error)
}

type dependencyServiceClient struct {
	cc *grpc.ClientConn
}

func NewDependencyServiceClient(cc *grpc.ClientConn) DependencyServiceClient {
	return &dependencyServiceClient{cc}
}

func (c *dependencyServiceClient) ListDependents(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (*ListDependentsResponse, error) {
	out := new(ListDependentsResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.api.v1alpha.tracker.DependencyService/ListDependents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependencyServiceClient) ListDependencies(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (*ListDependenciesResponse, error) {
	out := new(ListDependenciesResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.api.v1alpha.tracker.DependencyService/ListDependencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DependencyServiceServer is the server API for DependencyService service.
type DependencyServiceServer interface {
	ListDependents(context.Context, *DependencyRequest) (*ListDependentsResponse, error)
	ListDependencies(context.Context, *DependencyRequest) (*ListDependenciesResponse, error)
}

// UnimplementedDependencyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDependencyServiceServer struct {
}

func (*UnimplementedDependencyServiceServer) ListDependents(ctx context.Context, req *DependencyRequest) (*ListDependentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDependents not implemented")
}
func (*UnimplementedDependencyServiceServer) ListDependencies(ctx context.Context, req *DependencyRequest) (*ListDependenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDependencies not implemented")
}

func RegisterDependencyServiceServer(s *grpc.Server, srv DependencyServiceServer) {
	s.RegisterService(&_DependencyService_serviceDesc, srv)
}

func _DependencyService_ListDependents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyServiceServer).ListDependents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.api.v1alpha.tracker.DependencyService/ListDependents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyServiceServer).ListDependents(ctx, req.(*DependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependencyService_ListDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyServiceServer).ListDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.api.v1alpha.tracker.DependencyService/ListDependencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyServiceServer).ListDependencies(ctx, req.(*DependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DependencyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.deps.api.v1alpha.tracker.DependencyService",
	HandlerType: (*DependencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDependents",
			Handler:    _DependencyService_ListDependents_Handler,
		},
		{
			MethodName: "ListDependencies",
			Handler:    _DependencyService_ListDependencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha/tracker/tracker.proto",
}

// TopologyServiceClient is the client API for TopologyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopologyServiceClient interface {
	ListDependentsTopology(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (*ListDependentsResponse, error)
	ListDependentsTopologyTiered(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (*ListDependentsTieredResponse, error)
	ListDependenciesTopology(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (*ListDependenciesResponse, error)
	ListDependenciesTopologyTiered(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (*ListDependenciesTieredResponse, error)
}

type topologyServiceClient struct {
	cc *grpc.ClientConn
}

func NewTopologyServiceClient(cc *grpc.ClientConn) TopologyServiceClient {
	return &topologyServiceClient{cc}
}

func (c *topologyServiceClient) ListDependentsTopology(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (*ListDependentsResponse, error) {
	out := new(ListDependentsResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.api.v1alpha.tracker.TopologyService/ListDependentsTopology", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyServiceClient) ListDependentsTopologyTiered(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (*ListDependentsTieredResponse, error) {
	out := new(ListDependentsTieredResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.api.v1alpha.tracker.TopologyService/ListDependentsTopologyTiered", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyServiceClient) ListDependenciesTopology(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (*ListDependenciesResponse, error) {
	out := new(ListDependenciesResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.api.v1alpha.tracker.TopologyService/ListDependenciesTopology", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyServiceClient) ListDependenciesTopologyTiered(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (*ListDependenciesTieredResponse, error) {
	out := new(ListDependenciesTieredResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.api.v1alpha.tracker.TopologyService/ListDependenciesTopologyTiered", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopologyServiceServer is the server API for TopologyService service.
type TopologyServiceServer interface {
	ListDependentsTopology(context.Context, *DependencyRequest) (*ListDependentsResponse, error)
	ListDependentsTopologyTiered(context.Context, *DependencyRequest) (*ListDependentsTieredResponse, error)
	ListDependenciesTopology(context.Context, *DependencyRequest) (*ListDependenciesResponse, error)
	ListDependenciesTopologyTiered(context.Context, *DependencyRequest) (*ListDependenciesTieredResponse, error)
}

// UnimplementedTopologyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTopologyServiceServer struct {
}

func (*UnimplementedTopologyServiceServer) ListDependentsTopology(ctx context.Context, req *DependencyRequest) (*ListDependentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDependentsTopology not implemented")
}
func (*UnimplementedTopologyServiceServer) ListDependentsTopologyTiered(ctx context.Context, req *DependencyRequest) (*ListDependentsTieredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDependentsTopologyTiered not implemented")
}
func (*UnimplementedTopologyServiceServer) ListDependenciesTopology(ctx context.Context, req *DependencyRequest) (*ListDependenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDependenciesTopology not implemented")
}
func (*UnimplementedTopologyServiceServer) ListDependenciesTopologyTiered(ctx context.Context, req *DependencyRequest) (*ListDependenciesTieredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDependenciesTopologyTiered not implemented")
}

func RegisterTopologyServiceServer(s *grpc.Server, srv TopologyServiceServer) {
	s.RegisterService(&_TopologyService_serviceDesc, srv)
}

func _TopologyService_ListDependentsTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyServiceServer).ListDependentsTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.api.v1alpha.tracker.TopologyService/ListDependentsTopology",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyServiceServer).ListDependentsTopology(ctx, req.(*DependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyService_ListDependentsTopologyTiered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyServiceServer).ListDependentsTopologyTiered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.api.v1alpha.tracker.TopologyService/ListDependentsTopologyTiered",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyServiceServer).ListDependentsTopologyTiered(ctx, req.(*DependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyService_ListDependenciesTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyServiceServer).ListDependenciesTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.api.v1alpha.tracker.TopologyService/ListDependenciesTopology",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyServiceServer).ListDependenciesTopology(ctx, req.(*DependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyService_ListDependenciesTopologyTiered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyServiceServer).ListDependenciesTopologyTiered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.api.v1alpha.tracker.TopologyService/ListDependenciesTopologyTiered",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyServiceServer).ListDependenciesTopologyTiered(ctx, req.(*DependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TopologyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.deps.api.v1alpha.tracker.TopologyService",
	HandlerType: (*TopologyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDependentsTopology",
			Handler:    _TopologyService_ListDependentsTopology_Handler,
		},
		{
			MethodName: "ListDependentsTopologyTiered",
			Handler:    _TopologyService_ListDependentsTopologyTiered_Handler,
		},
		{
			MethodName: "ListDependenciesTopology",
			Handler:    _TopologyService_ListDependenciesTopology_Handler,
		},
		{
			MethodName: "ListDependenciesTopologyTiered",
			Handler:    _TopologyService_ListDependenciesTopologyTiered_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha/tracker/tracker.proto",
}
