version: "3.8"

networks:
  depscloud:

services:
  postgres:
    image: postgres:13.4
    hostname: postgres
    networks:
      - depscloud
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: depscloud
    ports:
    - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080
    networks:
      - depscloud

  tracker:
    restart: on-failure
    image: depscloud/tracker:${TRACKER_VERSION:-latest}
    hostname: tracker
    networks:
      - depscloud
    depends_on:
    - postgres
    command:
    - --storage-driver=postgres
    - --storage-address=postgres://user:password@postgres:5432/depscloud

  extractor:
    image: depscloud/extractor:${EXTRACTOR_VERSION:-latest}
    hostname: extractor
    networks:
      - depscloud

  indexer:
    restart: on-failure
    image: depscloud/indexer:${INDEXER_VERSION:-latest}
    hostname: indexer
    networks:
      - depscloud
    depends_on:
    - extractor
    - tracker
    volumes:
    - ./config.yaml:/etc/indexer/config.yaml
    command:
    - --config=/etc/indexer/config.yaml
    - --workers=1

  gateway:
    image: depscloud/gateway:${GATEWAY_VERSION:-latest}
    hostname: gateway
    networks:
      - depscloud
    depends_on:
    - extractor
    - tracker
    ports:
    - 8080:8080
