project_name: depscloud

snapshot:
  name_template: "{{ .ShortCommit }}"

builds:
  # deps command line interface
  - id: deps
    dir: services/deps
    main: ./main.go
    binary: deps
    ldflags:
      - -s -w
      - -X github.com/depscloud/depscloud/internal/appconf.Version={{.Version}}
      - -X github.com/depscloud/depscloud/internal/appconf.Commit={{.Commit}}
      - -X github.com/depscloud/depscloud/internal/appconf.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  # gateway service
  - id: gateway
    dir: services/gateway
    main: ./main.go
    binary: gateway
    ldflags:
      - -s -w
      - -X github.com/depscloud/depscloud/internal/appconf.Version={{.Version}}
      - -X github.com/depscloud/depscloud/internal/appconf.Commit={{.Commit}}
      - -X github.com/depscloud/depscloud/internal/appconf.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  # indexing cron
  - id: indexer
    dir: services/indexer
    main: ./main.go
    binary: indexer
    ldflags:
      - -s -w
      - -X github.com/depscloud/depscloud/internal/appconf.Version={{.Version}}
      - -X github.com/depscloud/depscloud/internal/appconf.Commit={{.Commit}}
      - -X github.com/depscloud/depscloud/internal/appconf.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  # tracker service
  - id: tracker
    dir: services/tracker
    main: ./main.go
    binary: tracker
    ldflags:
      - -s -w
      - -X github.com/depscloud/depscloud/internal/appconf.Version={{.Version}}
      - -X github.com/depscloud/depscloud/internal/appconf.Commit={{.Commit}}
      - -X github.com/depscloud/depscloud/internal/appconf.Date={{.Date}}
    # don't set cgo, otherwise sqlite won't work
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: deps
    name_template: "deps_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    builds:
      - deps
  - id: gateway
    name_template: "gateway_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    builds:
      - gateway
  - id: indexer
    name_template: "indexer_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    builds:
      - indexer
  - id: tracker
    name_template: "tracker_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    builds:
      - tracker

brews:
  # deps command line interface
  - name: depscloud-cli
    ids:
      - deps
    goarm: 7
    tap:
      owner: depscloud
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: mjpitz@deps.cloud
    homepage: https://deps.cloud/
    description: Command line interface to the deps.cloud API
    install: |
      bin.install "deps"

nfpms:
  - id: depscloud-cli-deb
    package_name: depscloud-cli
    file_name_template: "depscloud-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - deps
    vendor: deps.cloud
    homepage: https://deps.cloud/
    maintainer: mjpitz@deps.cloud
    description: Command line interface to the deps.cloud API.
    license: MIT
    formats:
      - deb

blobs:
  - provider: s3
    endpoint: https://sfo2.digitaloceanspaces.com
    region: us-west-2
    bucket: depscloud-artifacts
    ids:
      - deps
      - gateway
      - indexer
      - tracker
      - depscloud-cli
      - depscloud-cli-deb
    extra_files:
      - glob: ./dist/checksums.txt
      - glob: ./changelog*

checksum:
  name_template: 'checksums.txt'
