FROM golang:1.12

RUN go get golang.org/x/lint/golint

ENV GO111MODULE on

WORKDIR /go/src/indexer

COPY . .

RUN make deps && make test && make install

RUN useradd -ms /bin/sh indexer
WORKDIR /home/indexer
USER indexer

ENTRYPOINT [ "indexer" ]
