#!/bin/sh

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

if [[ "${ARCH}" == "x86_64" ]]; then
    ARCH=amd64
elif [[ "${ARCH}" == "i386" ]]; then
    ARCH=386
elif [[ "${ARCH}" == "aarch64" ]]; then
    ARCH=arm64
else
    ARCH=arm
fi

if [[ $# -lt 2 ]]; then
cat <<EOF
  usage: install-depscloud-binary <app> <version>
EOF
exit 1
fi

readonly APP="${1}"
readonly APP_VERSION="${2}"

echo <<EOF
  os:       ${OS}
  arch:     ${ARCH}
  app:      ${APP}
  version:  ${APP_VERSION}
EOF

curl -L -o ${APP} https://github.com/deps-cloud/${APP}/releases/download/v${APP_VERSION}/${APP}_${OS}_${ARCH}
chmod 755 ${APP}
mv ${APP} /bin/depscloud--${APP}
