FROM depscloud/devbase:latest AS builder

WORKDIR /go/src/gateway

COPY go.mod .
COPY go.sum .
COPY Makefile .
RUN make build-deps deps

COPY . .
RUN make test install

FROM depscloud/runtime:latest

COPY --from=builder /go/bin/gateway /usr/bin/gateway

ENTRYPOINT [ "/usr/bin/gateway" ]
