FROM golang:1.14

RUN go get golang.org/x/lint/golint

ENV GO111MODULE on

WORKDIR /go/src/gateway

COPY go.mod .
COPY go.sum .
COPY Makefile .

RUN make deps

COPY . .
RUN make test install

RUN useradd -ms /bin/sh gateway
WORKDIR /home/gateway
USER gateway

ENTRYPOINT [ "gateway" ]
