FROM golang:1.14

RUN go get golang.org/x/lint/golint

ENV GO111MODULE on

WORKDIR /go/src/indexer

COPY go.mod go.mod
COPY go.sum go.sum
COPY Makefile Makefile

RUN make deps

COPY . .

RUN make test install

RUN useradd -ms /bin/sh indexer
WORKDIR /home/indexer
USER indexer

ENTRYPOINT [ "indexer" ]
