FROM depscloud/devbase:latest AS builder

WORKDIR /go/src/indexer

COPY go.mod .
COPY go.sum .
COPY Makefile .
RUN make build-deps deps

COPY . .
RUN make test install

FROM depscloud/runtime:latest

COPY --from=builder /go/bin/indexer /usr/bin/indexer

ENTRYPOINT [ "/usr/bin/indexer" ]
