{
 "title": "deps.cloud",
 "description": "Dashboard for monitoring the deps.cloud system",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"depscloud\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"depscloud\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Disk Write IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"depscloud\"}[1m])) by (pod)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk Read IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"depscloud\"}[1m])) by (pod)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"depscloud\"}[1m])))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"depscloud\"}[1m])))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"depscloud\"}[1m])))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"depscloud\"}[1m])))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"depscloud\"}[1m])))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"depscloud\"}[1m])))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path)(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"depscloud\"}[1m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"depscloud\", status =~ \"[4-5].*\"}[1m]))\n / sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count{ingress = \"depscloud\"}[1m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"depscloud\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace = \"depscloud\"} / 1024 / 1024) by (pod)"
    }
   ]
  },
  {
   "title": "Storage Requests GB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"depscloud\"} / 1024 / 1024 / 1024) by (persistentvolumeclaim)\n",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  }
 ]
}