ARG NODE_VERSION=12

FROM node:${NODE_VERSION}

WORKDIR /home/depscloud
RUN apt-get update && apt-get install -y jq

COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . .
RUN npm run build && \
    npm run lint && \
    npm run test && \
    npm run prepackage

WORKDIR /home/depscloud
USER 13490:13490

ENTRYPOINT [ "npm", "start", "--" ]
