FROM ocr.sh/depscloud/download:latest AS installer

ARG HEALTH_PROBE_VERSION=0.3.1

RUN install-grpc-probe ${HEALTH_PROBE_VERSION}

FROM node:10 AS builder

WORKDIR /home/depscloud
RUN apt-get update && apt-get install -y jq

COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . .
RUN npm run build && \
    npm run lint && \
    npm run test && \
    npm run prepackage

FROM node:10

COPY --from=installer /usr/bin/grpc_health_probe /usr/bin/grpc_health_probe
COPY --from=builder /home/depscloud /home/depscloud

WORKDIR /home/depscloud
USER 13490:13490

ENTRYPOINT [ "npm", "start", "--" ]
