# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from depscloud_api.v1alpha.store import store_pb2 as depscloud__api_dot_v1alpha_dot_store_dot_store__pb2


class GraphStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/cloud.deps.api.v1alpha.store.GraphStore/Put',
                request_serializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.PutRequest.SerializeToString,
                response_deserializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.PutResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/cloud.deps.api.v1alpha.store.GraphStore/Delete',
                request_serializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.DeleteRequest.SerializeToString,
                response_deserializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.DeleteResponse.FromString,
                )
        self.List = channel.unary_unary(
                '/cloud.deps.api.v1alpha.store.GraphStore/List',
                request_serializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.ListRequest.SerializeToString,
                response_deserializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.ListResponse.FromString,
                )
        self.FindUpstream = channel.unary_unary(
                '/cloud.deps.api.v1alpha.store.GraphStore/FindUpstream',
                request_serializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.FindRequest.SerializeToString,
                response_deserializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.FindResponse.FromString,
                )
        self.FindDownstream = channel.unary_unary(
                '/cloud.deps.api.v1alpha.store.GraphStore/FindDownstream',
                request_serializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.FindRequest.SerializeToString,
                response_deserializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.FindResponse.FromString,
                )


class GraphStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindUpstream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindDownstream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.PutRequest.FromString,
                    response_serializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.PutResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.DeleteRequest.FromString,
                    response_serializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.DeleteResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.ListRequest.FromString,
                    response_serializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.ListResponse.SerializeToString,
            ),
            'FindUpstream': grpc.unary_unary_rpc_method_handler(
                    servicer.FindUpstream,
                    request_deserializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.FindRequest.FromString,
                    response_serializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.FindResponse.SerializeToString,
            ),
            'FindDownstream': grpc.unary_unary_rpc_method_handler(
                    servicer.FindDownstream,
                    request_deserializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.FindRequest.FromString,
                    response_serializer=depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.FindResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.deps.api.v1alpha.store.GraphStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GraphStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.deps.api.v1alpha.store.GraphStore/Put',
            depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.PutRequest.SerializeToString,
            depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.PutResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.deps.api.v1alpha.store.GraphStore/Delete',
            depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.DeleteRequest.SerializeToString,
            depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.deps.api.v1alpha.store.GraphStore/List',
            depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.ListRequest.SerializeToString,
            depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.ListResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindUpstream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.deps.api.v1alpha.store.GraphStore/FindUpstream',
            depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.FindRequest.SerializeToString,
            depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.FindResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindDownstream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.deps.api.v1alpha.store.GraphStore/FindDownstream',
            depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.FindRequest.SerializeToString,
            depscloud__api_dot_v1alpha_dot_store_dot_store__pb2.FindResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
