FROM depscloud/devbase:latest AS builder

WORKDIR /go/src/tracker

COPY go.mod .
COPY go.sum .
COPY Makefile .
RUN make build-deps deps

COPY . .
RUN make test install

FROM depscloud/runtime:latest

COPY --from=builder /go/bin/grpc-health-probe /usr/bin/grpc_health_probe
COPY --from=builder /go/bin/tracker /usr/bin/tracker

ENTRYPOINT [ "/usr/bin/tracker" ]
