ARG GO_VERSION=1.14
ARG ALPINE_VERSION=3.12

FROM golang:${GO_VERSION}-alpine${ALPINE_VERSION} AS builder

RUN apk -U upgrade && apk add build-base git ca-certificates sqlite bash curl

ENV GO111MODULE on

WORKDIR /go/src/tracker

COPY go.mod .
COPY go.sum .
COPY Makefile .
RUN make build-deps deps

COPY . .
RUN make test install

FROM depscloud/runtime:latest

COPY --from=builder /go/bin/tracker /usr/bin/tracker

ENTRYPOINT [ "/usr/bin/tracker" ]
