// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: config.proto

package config

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CloneStrategy int32

const (
	CloneStrategy_SSH  CloneStrategy = 0
	CloneStrategy_HTTP CloneStrategy = 1
)

var CloneStrategy_name = map[int32]string{
	0: "SSH",
	1: "HTTP",
}

var CloneStrategy_value = map[string]int32{
	"SSH":  0,
	"HTTP": 1,
}

func (x CloneStrategy) String() string {
	return proto.EnumName(CloneStrategy_name, int32(x))
}

func (CloneStrategy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

type Clone struct {
	Strategy             CloneStrategy `protobuf:"varint,1,opt,name=strategy,proto3,enum=cloud.deps.indexer.config.CloneStrategy" json:"strategy,omitempty"`
	Basic                *Basic        `protobuf:"bytes,2,opt,name=basic,proto3" json:"basic,omitempty"`
	PublicKey            *PublicKey    `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Clone) Reset()         { *m = Clone{} }
func (m *Clone) String() string { return proto.CompactTextString(m) }
func (*Clone) ProtoMessage()    {}
func (*Clone) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}
func (m *Clone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clone.Unmarshal(m, b)
}
func (m *Clone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clone.Marshal(b, m, deterministic)
}
func (m *Clone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clone.Merge(m, src)
}
func (m *Clone) XXX_Size() int {
	return xxx_messageInfo_Clone.Size(m)
}
func (m *Clone) XXX_DiscardUnknown() {
	xxx_messageInfo_Clone.DiscardUnknown(m)
}

var xxx_messageInfo_Clone proto.InternalMessageInfo

func (m *Clone) GetStrategy() CloneStrategy {
	if m != nil {
		return m.Strategy
	}
	return CloneStrategy_SSH
}

func (m *Clone) GetBasic() *Basic {
	if m != nil {
		return m.Basic
	}
	return nil
}

func (m *Clone) GetPublicKey() *PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type PublicKey struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	PrivateKeyPath       string   `protobuf:"bytes,2,opt,name=private_key_path,json=privateKeyPath,proto3" json:"private_key_path,omitempty"`
	PrivateKey           string   `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}
func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (m *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(m, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *PublicKey) GetPrivateKeyPath() string {
	if m != nil {
		return m.PrivateKeyPath
	}
	return ""
}

func (m *PublicKey) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *PublicKey) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Basic struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Basic) Reset()         { *m = Basic{} }
func (m *Basic) String() string { return proto.CompactTextString(m) }
func (*Basic) ProtoMessage()    {}
func (*Basic) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}
func (m *Basic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Basic.Unmarshal(m, b)
}
func (m *Basic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Basic.Marshal(b, m, deterministic)
}
func (m *Basic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Basic.Merge(m, src)
}
func (m *Basic) XXX_Size() int {
	return xxx_messageInfo_Basic.Size(m)
}
func (m *Basic) XXX_DiscardUnknown() {
	xxx_messageInfo_Basic.DiscardUnknown(m)
}

var xxx_messageInfo_Basic proto.InternalMessageInfo

func (m *Basic) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Basic) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type OAuthToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ApplicationId        string   `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuthToken) Reset()         { *m = OAuthToken{} }
func (m *OAuthToken) String() string { return proto.CompactTextString(m) }
func (*OAuthToken) ProtoMessage()    {}
func (*OAuthToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}
func (m *OAuthToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthToken.Unmarshal(m, b)
}
func (m *OAuthToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthToken.Marshal(b, m, deterministic)
}
func (m *OAuthToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthToken.Merge(m, src)
}
func (m *OAuthToken) XXX_Size() int {
	return xxx_messageInfo_OAuthToken.Size(m)
}
func (m *OAuthToken) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthToken.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthToken proto.InternalMessageInfo

func (m *OAuthToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *OAuthToken) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

type OAuth2Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Expiry               string   `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuth2Token) Reset()         { *m = OAuth2Token{} }
func (m *OAuth2Token) String() string { return proto.CompactTextString(m) }
func (*OAuth2Token) ProtoMessage()    {}
func (*OAuth2Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}
func (m *OAuth2Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuth2Token.Unmarshal(m, b)
}
func (m *OAuth2Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuth2Token.Marshal(b, m, deterministic)
}
func (m *OAuth2Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuth2Token.Merge(m, src)
}
func (m *OAuth2Token) XXX_Size() int {
	return xxx_messageInfo_OAuth2Token.Size(m)
}
func (m *OAuth2Token) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuth2Token.DiscardUnknown(m)
}

var xxx_messageInfo_OAuth2Token proto.InternalMessageInfo

func (m *OAuth2Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *OAuth2Token) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *OAuth2Token) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *OAuth2Token) GetExpiry() string {
	if m != nil {
		return m.Expiry
	}
	return ""
}

type Github struct {
	BaseUrl              string        `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	UploadUrl            string        `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	Users                []string      `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Organizations        []string      `protobuf:"bytes,4,rep,name=organizations,proto3" json:"organizations,omitempty"`
	Strategy             CloneStrategy `protobuf:"varint,5,opt,name=strategy,proto3,enum=cloud.deps.indexer.config.CloneStrategy" json:"strategy,omitempty"` // Deprecated: Do not use.
	Clone                *Clone        `protobuf:"bytes,6,opt,name=clone,proto3" json:"clone,omitempty"`
	Oauth2               *OAuth2Token  `protobuf:"bytes,10,opt,name=oauth2,proto3" json:"oauth2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Github) Reset()         { *m = Github{} }
func (m *Github) String() string { return proto.CompactTextString(m) }
func (*Github) ProtoMessage()    {}
func (*Github) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{5}
}
func (m *Github) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Github.Unmarshal(m, b)
}
func (m *Github) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Github.Marshal(b, m, deterministic)
}
func (m *Github) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Github.Merge(m, src)
}
func (m *Github) XXX_Size() int {
	return xxx_messageInfo_Github.Size(m)
}
func (m *Github) XXX_DiscardUnknown() {
	xxx_messageInfo_Github.DiscardUnknown(m)
}

var xxx_messageInfo_Github proto.InternalMessageInfo

func (m *Github) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *Github) GetUploadUrl() string {
	if m != nil {
		return m.UploadUrl
	}
	return ""
}

func (m *Github) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Github) GetOrganizations() []string {
	if m != nil {
		return m.Organizations
	}
	return nil
}

// Deprecated: Do not use.
func (m *Github) GetStrategy() CloneStrategy {
	if m != nil {
		return m.Strategy
	}
	return CloneStrategy_SSH
}

func (m *Github) GetClone() *Clone {
	if m != nil {
		return m.Clone
	}
	return nil
}

func (m *Github) GetOauth2() *OAuth2Token {
	if m != nil {
		return m.Oauth2
	}
	return nil
}

type Gitlab struct {
	BaseUrl              string        `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Users                []string      `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Groups               []string      `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	Strategy             CloneStrategy `protobuf:"varint,5,opt,name=strategy,proto3,enum=cloud.deps.indexer.config.CloneStrategy" json:"strategy,omitempty"` // Deprecated: Do not use.
	Clone                *Clone        `protobuf:"bytes,6,opt,name=clone,proto3" json:"clone,omitempty"`
	Private              *OAuthToken   `protobuf:"bytes,10,opt,name=private,proto3" json:"private,omitempty"`
	Oauth                *OAuthToken   `protobuf:"bytes,11,opt,name=oauth,proto3" json:"oauth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Gitlab) Reset()         { *m = Gitlab{} }
func (m *Gitlab) String() string { return proto.CompactTextString(m) }
func (*Gitlab) ProtoMessage()    {}
func (*Gitlab) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{6}
}
func (m *Gitlab) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gitlab.Unmarshal(m, b)
}
func (m *Gitlab) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gitlab.Marshal(b, m, deterministic)
}
func (m *Gitlab) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gitlab.Merge(m, src)
}
func (m *Gitlab) XXX_Size() int {
	return xxx_messageInfo_Gitlab.Size(m)
}
func (m *Gitlab) XXX_DiscardUnknown() {
	xxx_messageInfo_Gitlab.DiscardUnknown(m)
}

var xxx_messageInfo_Gitlab proto.InternalMessageInfo

func (m *Gitlab) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *Gitlab) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Gitlab) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

// Deprecated: Do not use.
func (m *Gitlab) GetStrategy() CloneStrategy {
	if m != nil {
		return m.Strategy
	}
	return CloneStrategy_SSH
}

func (m *Gitlab) GetClone() *Clone {
	if m != nil {
		return m.Clone
	}
	return nil
}

func (m *Gitlab) GetPrivate() *OAuthToken {
	if m != nil {
		return m.Private
	}
	return nil
}

func (m *Gitlab) GetOauth() *OAuthToken {
	if m != nil {
		return m.Oauth
	}
	return nil
}

type Bitbucket struct {
	Users                []string      `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Teams                []string      `protobuf:"bytes,4,rep,name=teams,proto3" json:"teams,omitempty"`
	Strategy             CloneStrategy `protobuf:"varint,5,opt,name=strategy,proto3,enum=cloud.deps.indexer.config.CloneStrategy" json:"strategy,omitempty"` // Deprecated: Do not use.
	Clone                *Clone        `protobuf:"bytes,6,opt,name=clone,proto3" json:"clone,omitempty"`
	Basic                *Basic        `protobuf:"bytes,10,opt,name=basic,proto3" json:"basic,omitempty"`
	Oauth                *OAuthToken   `protobuf:"bytes,11,opt,name=oauth,proto3" json:"oauth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Bitbucket) Reset()         { *m = Bitbucket{} }
func (m *Bitbucket) String() string { return proto.CompactTextString(m) }
func (*Bitbucket) ProtoMessage()    {}
func (*Bitbucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{7}
}
func (m *Bitbucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bitbucket.Unmarshal(m, b)
}
func (m *Bitbucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bitbucket.Marshal(b, m, deterministic)
}
func (m *Bitbucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bitbucket.Merge(m, src)
}
func (m *Bitbucket) XXX_Size() int {
	return xxx_messageInfo_Bitbucket.Size(m)
}
func (m *Bitbucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bitbucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bitbucket proto.InternalMessageInfo

func (m *Bitbucket) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Bitbucket) GetTeams() []string {
	if m != nil {
		return m.Teams
	}
	return nil
}

// Deprecated: Do not use.
func (m *Bitbucket) GetStrategy() CloneStrategy {
	if m != nil {
		return m.Strategy
	}
	return CloneStrategy_SSH
}

func (m *Bitbucket) GetClone() *Clone {
	if m != nil {
		return m.Clone
	}
	return nil
}

func (m *Bitbucket) GetBasic() *Basic {
	if m != nil {
		return m.Basic
	}
	return nil
}

func (m *Bitbucket) GetOauth() *OAuthToken {
	if m != nil {
		return m.Oauth
	}
	return nil
}

type Generic struct {
	BaseUrl              string   `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	PerPageParameter     string   `protobuf:"bytes,3,opt,name=per_page_parameter,json=perPageParameter,proto3" json:"per_page_parameter,omitempty"`
	PageParameter        string   `protobuf:"bytes,4,opt,name=page_parameter,json=pageParameter,proto3" json:"page_parameter,omitempty"`
	PageSize             int32    `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Selector             string   `protobuf:"bytes,6,opt,name=selector,proto3" json:"selector,omitempty"`
	Clone                *Clone   `protobuf:"bytes,7,opt,name=clone,proto3" json:"clone,omitempty"`
	Basic                *Basic   `protobuf:"bytes,10,opt,name=basic,proto3" json:"basic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Generic) Reset()         { *m = Generic{} }
func (m *Generic) String() string { return proto.CompactTextString(m) }
func (*Generic) ProtoMessage()    {}
func (*Generic) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{8}
}
func (m *Generic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Generic.Unmarshal(m, b)
}
func (m *Generic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Generic.Marshal(b, m, deterministic)
}
func (m *Generic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Generic.Merge(m, src)
}
func (m *Generic) XXX_Size() int {
	return xxx_messageInfo_Generic.Size(m)
}
func (m *Generic) XXX_DiscardUnknown() {
	xxx_messageInfo_Generic.DiscardUnknown(m)
}

var xxx_messageInfo_Generic proto.InternalMessageInfo

func (m *Generic) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *Generic) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Generic) GetPerPageParameter() string {
	if m != nil {
		return m.PerPageParameter
	}
	return ""
}

func (m *Generic) GetPageParameter() string {
	if m != nil {
		return m.PageParameter
	}
	return ""
}

func (m *Generic) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Generic) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

func (m *Generic) GetClone() *Clone {
	if m != nil {
		return m.Clone
	}
	return nil
}

func (m *Generic) GetBasic() *Basic {
	if m != nil {
		return m.Basic
	}
	return nil
}

type Static struct {
	RepositoryUrls       []string `protobuf:"bytes,1,rep,name=repository_urls,json=repositoryUrls,proto3" json:"repository_urls,omitempty"`
	Clone                *Clone   `protobuf:"bytes,2,opt,name=clone,proto3" json:"clone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Static) Reset()         { *m = Static{} }
func (m *Static) String() string { return proto.CompactTextString(m) }
func (*Static) ProtoMessage()    {}
func (*Static) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{9}
}
func (m *Static) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Static.Unmarshal(m, b)
}
func (m *Static) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Static.Marshal(b, m, deterministic)
}
func (m *Static) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Static.Merge(m, src)
}
func (m *Static) XXX_Size() int {
	return xxx_messageInfo_Static.Size(m)
}
func (m *Static) XXX_DiscardUnknown() {
	xxx_messageInfo_Static.DiscardUnknown(m)
}

var xxx_messageInfo_Static proto.InternalMessageInfo

func (m *Static) GetRepositoryUrls() []string {
	if m != nil {
		return m.RepositoryUrls
	}
	return nil
}

func (m *Static) GetClone() *Clone {
	if m != nil {
		return m.Clone
	}
	return nil
}

type Rds struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rds) Reset()         { *m = Rds{} }
func (m *Rds) String() string { return proto.CompactTextString(m) }
func (*Rds) ProtoMessage()    {}
func (*Rds) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{10}
}
func (m *Rds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rds.Unmarshal(m, b)
}
func (m *Rds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rds.Marshal(b, m, deterministic)
}
func (m *Rds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rds.Merge(m, src)
}
func (m *Rds) XXX_Size() int {
	return xxx_messageInfo_Rds.Size(m)
}
func (m *Rds) XXX_DiscardUnknown() {
	xxx_messageInfo_Rds.DiscardUnknown(m)
}

var xxx_messageInfo_Rds proto.InternalMessageInfo

func (m *Rds) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type Account struct {
	Github               *Github    `protobuf:"bytes,1,opt,name=github,proto3" json:"github,omitempty"`
	Gitlab               *Gitlab    `protobuf:"bytes,2,opt,name=gitlab,proto3" json:"gitlab,omitempty"`
	Bitbucket            *Bitbucket `protobuf:"bytes,3,opt,name=bitbucket,proto3" json:"bitbucket,omitempty"`
	Generic              *Generic   `protobuf:"bytes,4,opt,name=generic,proto3" json:"generic,omitempty"`
	Static               *Static    `protobuf:"bytes,5,opt,name=static,proto3" json:"static,omitempty"`
	Rds                  *Rds       `protobuf:"bytes,6,opt,name=rds,proto3" json:"rds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{11}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetGithub() *Github {
	if m != nil {
		return m.Github
	}
	return nil
}

func (m *Account) GetGitlab() *Gitlab {
	if m != nil {
		return m.Gitlab
	}
	return nil
}

func (m *Account) GetBitbucket() *Bitbucket {
	if m != nil {
		return m.Bitbucket
	}
	return nil
}

func (m *Account) GetGeneric() *Generic {
	if m != nil {
		return m.Generic
	}
	return nil
}

func (m *Account) GetStatic() *Static {
	if m != nil {
		return m.Static
	}
	return nil
}

func (m *Account) GetRds() *Rds {
	if m != nil {
		return m.Rds
	}
	return nil
}

type Configuration struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{12}
}
func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (m *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(m, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterEnum("cloud.deps.indexer.config.CloneStrategy", CloneStrategy_name, CloneStrategy_value)
	proto.RegisterType((*Clone)(nil), "cloud.deps.indexer.config.Clone")
	proto.RegisterType((*PublicKey)(nil), "cloud.deps.indexer.config.PublicKey")
	proto.RegisterType((*Basic)(nil), "cloud.deps.indexer.config.Basic")
	proto.RegisterType((*OAuthToken)(nil), "cloud.deps.indexer.config.OAuthToken")
	proto.RegisterType((*OAuth2Token)(nil), "cloud.deps.indexer.config.OAuth2Token")
	proto.RegisterType((*Github)(nil), "cloud.deps.indexer.config.Github")
	proto.RegisterType((*Gitlab)(nil), "cloud.deps.indexer.config.Gitlab")
	proto.RegisterType((*Bitbucket)(nil), "cloud.deps.indexer.config.Bitbucket")
	proto.RegisterType((*Generic)(nil), "cloud.deps.indexer.config.Generic")
	proto.RegisterType((*Static)(nil), "cloud.deps.indexer.config.Static")
	proto.RegisterType((*Rds)(nil), "cloud.deps.indexer.config.Rds")
	proto.RegisterType((*Account)(nil), "cloud.deps.indexer.config.Account")
	proto.RegisterType((*Configuration)(nil), "cloud.deps.indexer.config.Configuration")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 863 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcd, 0x8e, 0x1b, 0x45,
	0x10, 0xc6, 0xf6, 0x7a, 0xec, 0x29, 0xc7, 0xcb, 0xaa, 0x15, 0x45, 0x13, 0x50, 0x60, 0x19, 0x12,
	0x58, 0x21, 0x64, 0x21, 0x23, 0x21, 0x21, 0x50, 0xa2, 0x78, 0x91, 0xb2, 0x51, 0x0e, 0xb1, 0xc6,
	0x9b, 0x0b, 0x17, 0xab, 0x3d, 0x53, 0x19, 0xb7, 0x76, 0x76, 0xa6, 0xd5, 0xdd, 0x03, 0xf1, 0x5e,
	0xb8, 0xf1, 0x38, 0x1c, 0x39, 0x73, 0xe6, 0xc6, 0x8b, 0xf0, 0x0c, 0xa8, 0xab, 0xdb, 0x7f, 0x11,
	0x99, 0x65, 0x85, 0x14, 0xe5, 0xd6, 0x55, 0xfd, 0x7d, 0xd5, 0x35, 0x5f, 0xfd, 0xd8, 0x70, 0x2b,
	0xad, 0xca, 0x97, 0x22, 0x1f, 0x49, 0x55, 0x99, 0x8a, 0xdd, 0x4d, 0x8b, 0xaa, 0xce, 0x46, 0x19,
	0x4a, 0x3d, 0x12, 0x65, 0x86, 0xaf, 0x50, 0x8d, 0x1c, 0x20, 0xfe, 0xb3, 0x05, 0xdd, 0xd3, 0xa2,
	0x2a, 0x91, 0xfd, 0x00, 0x7d, 0x6d, 0x14, 0x37, 0x98, 0xaf, 0xa2, 0xd6, 0x71, 0xeb, 0xe4, 0x70,
	0x7c, 0x32, 0x7a, 0x23, 0x6f, 0x44, 0x9c, 0x99, 0xc7, 0x27, 0x1b, 0x26, 0xfb, 0x06, 0xba, 0x0b,
	0xae, 0x45, 0x1a, 0xb5, 0x8f, 0x5b, 0x27, 0x83, 0xf1, 0x71, 0x43, 0x88, 0x89, 0xc5, 0x25, 0x0e,
	0xce, 0x4e, 0x01, 0x64, 0xbd, 0x28, 0x44, 0x3a, 0xbf, 0xc0, 0x55, 0xd4, 0x21, 0xf2, 0xfd, 0x06,
	0xf2, 0x94, 0xc0, 0xcf, 0x70, 0x95, 0x84, 0x72, 0x7d, 0x8c, 0x7f, 0x6d, 0x41, 0xb8, 0xb9, 0x60,
	0x0c, 0x0e, 0x6a, 0x8d, 0x8a, 0x3e, 0x26, 0x4c, 0xe8, 0xcc, 0x4e, 0xe0, 0x48, 0x2a, 0xf1, 0x13,
	0x37, 0x68, 0xdf, 0x99, 0x4b, 0x6e, 0x96, 0x94, 0x69, 0x98, 0x1c, 0x7a, 0xff, 0x33, 0x5c, 0x4d,
	0xb9, 0x59, 0xb2, 0x8f, 0x61, 0xb0, 0x83, 0xa4, 0x8c, 0xc2, 0x04, 0xb6, 0x20, 0xf6, 0x01, 0xf4,
	0x25, 0xd7, 0xfa, 0xe7, 0x4a, 0x65, 0xd1, 0x01, 0xdd, 0x6e, 0xec, 0xf8, 0x11, 0x74, 0xe9, 0xeb,
	0x2c, 0xc8, 0xbe, 0x5b, 0xf2, 0x4b, 0xf4, 0x79, 0x6c, 0xec, 0xbd, 0x00, 0xed, 0xd7, 0x02, 0x3c,
	0x05, 0x78, 0xfe, 0xb8, 0x36, 0xcb, 0xf3, 0xea, 0x02, 0x4b, 0x76, 0x1b, 0xba, 0xc6, 0x1e, 0x7c,
	0x08, 0x67, 0xb0, 0x07, 0x70, 0xc8, 0xa5, 0x2c, 0x44, 0xca, 0x8d, 0xa8, 0xca, 0xb9, 0x58, 0x47,
	0x19, 0xee, 0x78, 0x9f, 0x66, 0xf1, 0x2f, 0x30, 0xa0, 0x50, 0xe3, 0xa6, 0x58, 0xf7, 0x00, 0xe8,
	0x30, 0x37, 0x2b, 0x89, 0x3e, 0x4e, 0x48, 0x9e, 0xf3, 0x95, 0x44, 0xf6, 0x29, 0x0c, 0x15, 0xbe,
	0x54, 0xa8, 0x97, 0x73, 0x47, 0x76, 0x72, 0xdc, 0xf2, 0x4e, 0x17, 0xf9, 0x0e, 0x04, 0xf8, 0x4a,
	0x0a, 0xb5, 0xf2, 0x72, 0x78, 0x2b, 0xfe, 0xa3, 0x0d, 0xc1, 0x13, 0x61, 0x96, 0xf5, 0x82, 0xdd,
	0x85, 0xfe, 0x82, 0x6b, 0x9c, 0xd7, 0xaa, 0xf0, 0xef, 0xf7, 0xac, 0xfd, 0x42, 0x15, 0x36, 0x83,
	0x5a, 0x16, 0x15, 0xcf, 0xe8, 0xd2, 0x67, 0xe0, 0x3c, 0xf6, 0xfa, 0x36, 0x74, 0xad, 0x70, 0x3a,
	0xea, 0x1c, 0x77, 0x6c, 0xda, 0x64, 0xb0, 0xfb, 0x30, 0xac, 0x54, 0xce, 0x4b, 0x71, 0x45, 0x5f,
	0xab, 0xa3, 0x03, 0xba, 0xdd, 0x77, 0xb2, 0xb3, 0x9d, 0xce, 0xee, 0xde, 0xac, 0xb3, 0x27, 0xed,
	0xa8, 0xb5, 0xdf, 0xdd, 0xa9, 0xbd, 0x8e, 0x82, 0x6b, 0xbb, 0x9b, 0xc2, 0x24, 0x0e, 0xce, 0x1e,
	0x42, 0x50, 0x71, 0x5b, 0x83, 0x08, 0x88, 0xf8, 0x59, 0x03, 0x71, 0xa7, 0x58, 0x89, 0x67, 0xc5,
	0x7f, 0x39, 0x09, 0x0b, 0xde, 0x28, 0xe1, 0xbf, 0x6b, 0x74, 0x07, 0x82, 0x5c, 0x55, 0xb5, 0x5c,
	0x8b, 0xe3, 0xad, 0x77, 0x40, 0x95, 0x47, 0xd0, 0xf3, 0xf3, 0xe4, 0x65, 0x79, 0x70, 0x9d, 0x2c,
	0x4e, 0x95, 0x35, 0x8b, 0x7d, 0x07, 0x5d, 0x12, 0x28, 0x1a, 0xdc, 0x84, 0xee, 0x38, 0xf1, 0x6f,
	0x6d, 0x08, 0x27, 0xc2, 0x2c, 0xea, 0xf4, 0x02, 0xcd, 0x1b, 0xb4, 0xb3, 0xc3, 0x82, 0xfc, 0x72,
	0x2d, 0x9d, 0x33, 0xde, 0x01, 0xe5, 0x36, 0x5b, 0x16, 0x6e, 0xb6, 0x65, 0xff, 0x97, 0x60, 0xbf,
	0xb7, 0xa1, 0xf7, 0x04, 0x4b, 0x54, 0x22, 0x6d, 0xea, 0x42, 0x06, 0x07, 0x3b, 0x6b, 0x95, 0xce,
	0xec, 0x4b, 0x60, 0x12, 0xd5, 0x5c, 0xf2, 0x1c, 0xe7, 0x92, 0x2b, 0x7e, 0x89, 0x06, 0x95, 0x5f,
	0x22, 0x47, 0x12, 0xd5, 0x94, 0xe7, 0x38, 0x5d, 0xfb, 0xed, 0x62, 0x7b, 0x0d, 0xe9, 0x16, 0xca,
	0x50, 0xee, 0xc1, 0x3e, 0x84, 0x90, 0x60, 0x5a, 0x5c, 0x21, 0xd5, 0xa1, 0x6b, 0x17, 0x68, 0x8e,
	0x33, 0x71, 0x45, 0xcb, 0x55, 0x63, 0x81, 0xa9, 0xa9, 0x14, 0x89, 0x1b, 0x26, 0x1b, 0x7b, 0xab,
	0x7a, 0xef, 0xad, 0xa8, 0x1e, 0x0b, 0x08, 0x66, 0x86, 0x1b, 0x91, 0xb2, 0xcf, 0xe1, 0x7d, 0x85,
	0xb2, 0xd2, 0xc2, 0x54, 0x6a, 0x65, 0xc5, 0xd3, 0x51, 0x8b, 0x3a, 0xeb, 0x70, 0xeb, 0x7e, 0xa1,
	0x0a, 0xbd, 0x4d, 0xb1, 0x7d, 0xa3, 0x14, 0xe3, 0x7b, 0xd0, 0x49, 0x32, 0x9a, 0x79, 0xc3, 0x55,
	0x8e, 0xc6, 0x17, 0xc7, 0x5b, 0xf1, 0xdf, 0x6d, 0xe8, 0x3d, 0x4e, 0xd3, 0xaa, 0x2e, 0x0d, 0xfb,
	0x16, 0x82, 0x9c, 0xb6, 0x32, 0x61, 0x06, 0xe3, 0x4f, 0x1a, 0xde, 0x70, 0xeb, 0x3b, 0xf1, 0x04,
	0x4f, 0x2d, 0xf8, 0xc2, 0xa7, 0x77, 0x0d, 0xb5, 0xe0, 0x8e, 0x6a, 0xd7, 0xd7, 0x04, 0xc2, 0xc5,
	0x7a, 0xe8, 0xfe, 0xc3, 0xcf, 0xfc, 0x66, 0x40, 0x93, 0x2d, 0x8d, 0x7d, 0x0f, 0xbd, 0xdc, 0xf5,
	0x21, 0x35, 0xc6, 0x60, 0x1c, 0x37, 0xbd, 0xef, 0x90, 0xc9, 0x9a, 0x62, 0x93, 0xd7, 0x54, 0x0d,
	0xea, 0x99, 0xe6, 0xe4, 0x5d, 0xd9, 0x12, 0x4f, 0x60, 0x5f, 0x41, 0x47, 0x65, 0xda, 0x0f, 0xeb,
	0x47, 0x0d, 0xbc, 0x24, 0xd3, 0x89, 0x85, 0xc6, 0xcf, 0x61, 0x78, 0x4a, 0xae, 0x5a, 0xd1, 0x8f,
	0x11, 0x7b, 0x08, 0x7d, 0xee, 0x0a, 0xe0, 0x4a, 0xdf, 0x9c, 0xbc, 0xaf, 0x55, 0xb2, 0xe1, 0x7c,
	0x11, 0xc3, 0x70, 0x6f, 0xa1, 0xb0, 0x1e, 0x74, 0x66, 0xb3, 0xb3, 0xa3, 0xf7, 0x58, 0x1f, 0x0e,
	0xce, 0xce, 0xcf, 0xa7, 0x47, 0xad, 0x49, 0xff, 0xc7, 0xc0, 0xf1, 0x17, 0x01, 0xfd, 0xff, 0xfb,
	0xfa, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0x9a, 0x96, 0x9e, 0x0f, 0x0a, 0x00, 0x00,
}
