name: extractor-tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.12
    steps:
      - name: Prepare
        run: apk -U upgrade && apk add build-base git ca-certificates python2 python3 jq bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          make package-extractor VERSION=${GITHUB_REF##*/v}

      - name: Upload Release Assets
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: services/extractor/extractor-*
          tag: ${{ github.ref }}
          file_glob: true

  docker:
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Docker Registry
        run: echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USERNAME}" --password-stdin
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Container Image
        run: |
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            --build-arg BINARY=extractor \
            --build-arg VERSION=${GITHUB_REF##*/v} \
            --tag depscloud/extractor:latest \
            --tag depscloud/extractor:${GITHUB_REF##*/v} \
            -f dockerfiles/node-tag/Dockerfile \
            --push
